---
output:
  word_document: default
  html_document: default
---


```{r setup, include=FALSE}
# Load used packages
library(package = "readxl")
library(package = "tidyverse")

# configure ggplot2 theme
theme_set(
  theme_classic() +
    theme(
      title = element_text(face = "bold"),
      plot.subtitle = element_text(face = "plain")
    )
)

# configure knitting
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = "..")
```


```{r data}
# load data
source(file = "scripts/load-data.R")
```



# Lutzomyia diversity

## Data description

### Sex of collected specimens

```{r lutzomyia-sex-description}
lutzomyia_sex %>%
  mutate(
    sex = recode(
      sex,
      f = "female",
      m = "male"
    )
  ) %>%
  spread(key = sex, value = total_indivituals) %>%
  set_names(
    gsub("(^| )([a-z])", "\\1\\U\\2", gsub("_", " ", names(.)), perl = TRUE)
  ) %>%
  knitr::kable(
    caption = paste(
      "**Table 1:**",
      "Total individuals collected by species and sex" 
    )
  )
```


### Specimens by site

```{r lutzomyia-site-description}
lutzomyia %>%
  group_by(species, site) %>%
  summarize(
    n = n(),
    mean = mean(count),
    text = paste0(mean, " (", n, ")")
  ) %>%
  select(species, site, text) %>%
  spread(key = site, value = text) %>%
  set_names(
    gsub("(^| )([a-z])", "\\1\\U\\2", gsub("_", " ", names(.)), perl = TRUE)
  ) %>%
  set_names(
    ifelse(names(.) == "Species", names(.), paste0(names(.), ", mean (n)"))
  ) %>%
  knitr::kable(
    caption = paste(
      "**Table 2:**",
      "Mean number of collected individuals by species and forest fragmentation"
    )
  )
```


## Statistical analysis

### Species relative abundance between canopy and underbrush

> Pending vertical strata data

```{r vertical-relative-abundance}
#------------------------------------------------------------------------------*
# ldutari:
# Abundancia relative de especies mas abundantes entre dosel y el sotobosque,
# utilizando T-test y U de Mann- Whitney
#------------------------------------------------------------------------------*
```



### Diversity

```{r prepare-diversity-data}
#------------------------------------------------------------------------------*
# ldutari:
# Indices de diversidad y curvas de acumulacion
# (los indices pueden ser Alpha de Fisher, Margalef, Shannon, Simpson,
# Berger-Parker)
#------------------------------------------------------------------------------*

# All trap order permutations
trap_permutations <- lutzomyia %>%
  # For each site and its traps
  select(site, trap) %>%
  split(.$site) %>%
  map(unique) %>%
  # Calculate all permutations of traps (i.e. simulate order of use)
  map(~combinat::permn(.x$trap)) %>%
  # Put in nice rectangular structure
  map(simplify2array) %>%
  map(t) %>%
  map(as_data_frame) %>%
  # Combine everything
  bind_rows(.id = "site") %>%
  group_by(site) %>%
  mutate(permutation = 1:n()) %>%
  # Use tidy structure
  set_names(gsub("V", "", names(.))) %>%
  gather(key = effort, value = trap, convert = TRUE, -site, -permutation) %>%
  arrange(site, permutation)
```
